use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ResumeData {
    pub name: String,
    pub email: String,
    pub title: String,
    pub summary: String,
    pub skills: Vec<String>,
    pub projects: Vec<ResumeProjectData>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ResumeProjectData {
    pub name: String,
    pub description: String,
    pub technologies: Vec<String>,
    pub highlights: Vec<String>,
}

pub fn build_resume_json(
    user_name: &str,
    user_email: &str,
    projects: Vec<ResumeProjectData>,
) -> ResumeData {
    ResumeData {
        name: user_name.to_string(),
        email: user_email.to_string(),
        title: "Senior Full Stack Software Engineer".to_string(),
        summary: "Automated developer career profile generated by DevResume AI.".to_string(),
        skills: vec![
            "Rust".to_string(),
            "PostgreSQL".to_string(),
            "Next.js".to_string(),
            "Docker".to_string(),
        ],
        projects,
    }
}
